export default {
  // header
  settings: 'Settings',
  bookmarks: 'Bookmarks',
  recentNews: 'Recent News',
  searchedNews: 'Search Results',
  search: 'Search news',

  // buttons
  logout: 'Logout',
  comments: 'See all comments',
  cancel: 'Cancel',
  send: 'Send',
  // placeholders
  writeComment: 'Write a comment...',
  // category
  general: 'General',
  news: 'News',
  world: "World",
  legal: "Legal",
  business: 'Business',
  technology: "Technology",
  car: "Car",
  travel: "Travel",
  lifestyle: "Lifestyle",
  culture: "Culture",
  entertainment: 'Entertainment',
  sports: 'Sports',
  education: "Education",
  realEstate: "Real Estate",
  health: 'Health',
  science: 'Science',
  fact: "Fact",
  shared: "Shared",
  // preferences
  preferences: 'Preferences',
  mode: 'Dark mode',
  notification: 'Notifications',
  timeSpent: 'Time to read',
  lang: 'Language',
  help: 'Help and Suggestions',
  months: [
    'Jan',
    'Feb',
    'Mar',
    'Apr',
    'May',
    'Jun',
    'Jul',
    'Aug',
    'Sep',
    'Oct',
    'Nov',
    'Dec',
  ],
  //auth-login
  forgotPassword: 'Forgot your password ? ',
  resetPassword: 'Reset your password.',
  createAccount: "Don't have an account ? ",
  signUpNow: 'Sing up now!',
  password: 'Password',
  confirm: 'Confirm',
  email: 'Email',
  signup: 'Sign Up',
  enterEmail: 'Enter a Email',
  enterValidEmail: 'Enter a valid Email',
  enterPass: 'Enter a password',
  enterName: 'Enter your name',
  enterValidPass: 'Password must be 8 to 20 character',
  matchPass: 'Those passwords didn’t match',
  //auth-sign up
  name: 'Full name',
  haveAccount: 'Already have an account ? ',
  loginNow: 'Login now!',
  login: 'Login',
  loginSuccess: 'Login success!',
  signupSuccess: 'Signup success!',
  //columnist screen
  mentions: 'Mentions',
  yourMentions: 'Your Comments',
  mentioned: 'Mentioned',
  noComment: 'You have not commented yet.',
  //bookmark screen
  noBookmark: 'No bookmarks yet.',
  needLogin: "You are not logged in",
  home: "Home",
  user: "User",
};
