export default {
  // header
  settings: 'Cài đặt',
  bookmarks: 'Bookmarks',
  recentNews: 'Tin tức mới',
  searchedNews: 'Kết quả tìm kiểm',
  search: 'Tìm kiếm',
  // buttons
  logout: 'Đăng xuất',
  comments: 'Xem tất cả bình luận',
  cancel: 'Hủy bỏ',
  send: 'Gửi',
  // placeholders
  writeComment: 'Viết bình luận...',
  // category
  general: 'Tổng quan',
  news: 'Thời sự',
  world: "Thế giới",
  legal: "Pháp luật",
  business: 'Kinh doanh',
  technology: "Công nghệ",
  car: "Xe",
  travel: "Du lịch",
  lifestyle: "Nhịp sống trẻ",
  culture: "Văn hóa",
  entertainment: 'Giải trí',
  sports: 'Thể thao',
  education: "Giáo dục",
  realEstate: "Nhà đất",
  health: 'Sức khỏe',
  science: 'Khoa học',
  fact: "Giả thật",
  shared: "Bạn đọc",
  // preferences
  preferences: 'Sở thích',
  mode: 'Chế độ tối',
  notification: 'Thông báo',
  lang: 'Ngôn ngữ',
  help: 'Trợ giúp và Gợi ý',
  months: [
    'Th1',
    'Th2',
    'Th3',
    'Th4',
    'Th5',
    'Th6',
    'Th7',
    'Th8',
    'Th9',
    'Th10',
    'Th11',
    'Th12',
  ],
  //auth-login
  forgotPassword: 'Quên mật khẩu? ',
  resetPassword: 'Đặt lại mật khẩu.',
  createAccount: "Không có tài khoản? ",
  signUpNow: 'Đăng ký ngay!',
  password: 'Mật khẩu',
  confirm: 'Xác nhận',
  email: 'Email',
  signup: 'Đăng ký',
  enterEmail: 'Nhập một địa chỉ Email',
  enterValidEmail: 'Nhập một địa chỉ Email hợp lệ',
  enterPass: 'Nhập mật khẩu',
  enterName: 'Nhập họ và tên',
  enterValidPass: 'Mật khẩu phải có từ 8 đến 20 ký tự',
  matchPass: 'Mật khẩu không khớp',
  //auth-sign up
  name: 'Họ và tên',
  haveAccount: 'Đã có tài khoản? ',
  loginNow: 'Đăng nhập ngay!',
  login: 'Đăng nhập',
  loginSuccess: 'Đăng nhập thành công!',
  signupSuccess: 'Đăng ký thành công!',
  //columnist screen
  yourMentions: 'Bình luận của bạn',
  noComment: 'Bạn chưa có bình luận nào.',
  //bookmark screen
  noBookmark: 'Bạn chưa lưu bài báo nào.',
  needLogin: "Bạn chưa đăng nhập",
  home: "Trang chủ",
  user: "Người dùng",
};
